export default {
  semantic: [
    { label: "page background", color: "#ffffff" },
    { label: "$govuk-text-colour", color: "#0b0c0c" },
    { label: "$govuk-secondary-text-colour", color: "#505a5f" },
    { label: "$govuk-link-colour", color: "#1d70b8" },
    { label: "$govuk-link-hover-colour", color: "#003078" },
    { label: "$govuk-link-visited-colour", color: "#4c2c92" },
    { label: "$govuk-link-active-colour", color: "#0b0c0c" },
    { label: "$govuk-border-colour", color: "#b1b4b6" },
    { label: "$govuk-input-border-colour", color: "#0b0c0c" },
    { label: "$govuk-error-colour", color: "#d4351c" },
    { label: "$govuk-success-colour", color: "#00703c" },
    { label: "$govuk-brand-colour", color: "#1d70b8" },
  ],
  full: [
    { label: "black", color: "#0b0c0c" },
    { label: "dark grey", color: "#505a5f" },
    { label: "mid grey", color: "#b1b4b6" },
    { label: "light grey", color: "#f3f2f1" },
    { label: "white", color: "#ffffff" },
    { label: "red", color: "#d4351c" },
    { label: "yellow", color: "#ffdd00" },
    { label: "green", color: "#00703c" },
    { label: "blue", color: "#1d70b8" },
    { label: "dark blue", color: "#003078" },
    { label: "light blue", color: "#5694ca" },
    { label: "purple", color: "#4c2c92" },
    { label: "light purple", color: "#6f72af" },
    { label: "bright purple", color: "#912b88" },
    { label: "pink", color: "#d53880" },
    { label: "light pink", color: "#f499be" },
    { label: "orange", color: "#f47738" },
    { label: "brown", color: "#b58840" },
    { label: "light green", color: "#85994b" },
    { label: "turquoise", color: "#28a197" },
  ],
};
