export default {
  full: [
    { label: "Black", color: "#0B0C0C" },
    { label: "Black tint 25%", color: "#484949" },
    { label: "Black tint 50%", color: "#858686" },
    { label: "Black tint 80%", color: "#CECECE" },
    { label: "Black tint 95%", color: "#F3F3F3" },
    { label: "White", color: "#FFFFFF" },
    { label: "Primary blue", color: "#1D70B8" },
    { label: "Primary blue (dark mode)", color: "#37A3FF" },
    { label: "Blue tint 25%", color: "#5694CA" },
    { label: "Blue tint 50%", color: "#8EB8DC" },
    { label: "Blue tint 80%", color: "#D2E2F1" },
    { label: "Blue tint 95%", color: "#F4F8FB" },
    { label: "Blue shade 25%", color: "#16548A" },
    { label: "Blue shade 50%", color: "#0F385C" },
    { label: "Blue shade 80%", color: "#061625" },
    { label: "Accent blue", color: "#11E0F1" },
    { label: "Primary green", color: "#11875A" },
    { label: "Green tint 25%", color: "#4DA583" },
    { label: "Green tint 50%", color: "#88C3AD" },
    { label: "Green tint 80%", color: "#CFE7DE" },
    { label: "Green tint 95%", color: "#F3F9F7" },
    { label: "Green shade 25%", color: "#0D6544" },
    { label: "Green shade 50%", color: "#09442D" },
    { label: "Accent green", color: "#66F39E" },
    { label: "Primary teal", color: "#158187" },
    { label: "Teal tint 25%", color: "#50A1A5" },
    { label: "Teal tint 50%", color: "#8AC0C3" },
    { label: "Teal tint 80%", color: "#D0E6E7" },
    { label: "Teal tint 95%", color: "#F3F9F9" },
    { label: "Teal shade 25%", color: "#106165" },
    { label: "Teal shade 50%", color: "#0B4144" },
    { label: "Accent teal", color: "#00FFE0" },
    { label: "Primary purple", color: "#54319F" },
    { label: "Purple tint 25%", color: "#7F65B7" },
    { label: "Purple tint 50%", color: "#AA98CF" },
    { label: "Purple tint 80%", color: "#DDD6EC" },
    { label: "Purple tint 95%", color: "#F6F5FA" },
    { label: "Purple shade 25%", color: "#3F2577" },
    { label: "Purple shade 50%", color: "#2A1950" },
    { label: "Accent purple", color: "#BA4AFF" },
    { label: "Primary magenta", color: "#CA357C" },
    { label: "Magenta tint 25%", color: "#D7689D" },
    { label: "Magenta tint 50%", color: "#E59ABE" },
    { label: "Magenta tint 80%", color: "#F4D7E5" },
    { label: "Magenta tint 95%", color: "#FCF5F8" },
    { label: "Magenta shade 25%", color: "#98285D" },
    { label: "Magenta shade 50%", color: "#651B3E" },
    { label: "Accent magenta", color: "#FF52EE" },
    { label: "Primary red", color: "#CA3535" },
    { label: "Red tint 25%", color: "#D76868" },
    { label: "Red tint 50%", color: "#E59A9A" },
    { label: "Red tint 80%", color: "#F4D7D7" },
    { label: "Red tint 95%", color: "#FCF5F5" },
    { label: "Red shade 25%", color: "#982828" },
    { label: "Red shade 50%", color: "#651B1B" },
    { label: "Accent red", color: "#FF5E5E" },
    { label: "Primary orange", color: "#F47738" },
    { label: "Orange tint 25%", color: "#F7996A" },
    { label: "Orange tint 50%", color: "#FABB9C" },
    { label: "Orange tint 80%", color: "#FDE4D7" },
    { label: "Orange tint 95%", color: "#FEF8F5" },
    { label: "Orange shade 25%", color: "#B7592A" },
    { label: "Orange shade 50%", color: "#7A3C1C" },
    { label: "Accent orange", color: "#FFAF4A" },
    { label: "Primary yellow", color: "#FFDD00" },
    { label: "Yellow tint 25%", color: "#FFE640" },
    { label: "Yellow tint 50%", color: "#FFEE80" },
    { label: "Yellow tint 80%", color: "#FFF8CC" },
    { label: "Yellow tint 95%", color: "#FFFDF2" },
    { label: "Yellow shade 25%", color: "#BFA600" },
    { label: "Yellow shade 50%", color: "#806F00" },
    { label: "Accent yellow", color: "#FCFF52" },
    { label: "Primary brown", color: "#99704A" },
    { label: "Brown tint 25%", color: "#B39477" },
    { label: "Brown tint 50%", color: "#CCB8A5" },
    { label: "Brown tint 95%", color: "#FAF8F6" },
  ],
};
